package caddy

import (
	"fmt"
	"os"
	"path/filepath"
	"text/template"

	"github.com/aran/mdns-caddy/internal/cert"
	"github.com/aran/mdns-caddy/internal/profile"
)

// PortMapping defines a mapping from external (Caddy) port to internal (localhost) port
type PortMapping struct {
	ExternalPort int // The port Caddy listens on
	InternalPort int // The port on localhost to forward to
}

// DomainMapping represents a domain with its port mappings
type DomainMapping struct {
	Domain       string        // Domain name (e.g., dev.example.com)
	PortMappings []PortMapping // Port mappings for this domain
}

// CaddyDomainConfig holds domain-specific configuration for the Caddy template
type CaddyDomainConfig struct {
	Domain       string
	CertPath     string
	KeyPath      string
	PortMappings []PortMapping
}

// Config holds the data for the Caddy template
type Config struct {
	MDNSHostnames    []string
	ServerPort       int
	LocalTLSCertPath string
	LocalTLSKeyPath  string
	DomainConfigs    []CaddyDomainConfig
}

const DefaultConfigPath = "Caddyfile"

func GenerateConfig(
	mdnsHostnames []string,
	domainMappings []DomainMapping,
	serverPort int,
	outputPath string,
) (certGenerated bool, profileGenerated bool, err error) {
	if len(domainMappings) == 0 {
		return false, false, fmt.Errorf("no domains provided for Caddy configuration")
	}

	cwd, err := os.Getwd()
	if err != nil {
		return false, false, fmt.Errorf("error getting current directory: %w", err)
	}

	certManager := cert.NewManager(cwd)
	profileManager := profile.NewProfileManager(cwd)

	// Check if root CA exists
	_, err = os.Stat(certManager.Paths.RootCAPath)
	if err != nil {
		certGenerated = true
	}

	// Ensure the root CA exists
	if err := certManager.EnsureCA(); err != nil {
		return false, false, fmt.Errorf("error ensuring CA exists: %w", err)
	}

	// Generate certificate for mDNS hostnames
	localCertGenerated, err := certManager.EnsureLocalCertificate(mdnsHostnames)
	if err != nil {
		return false, false, fmt.Errorf("error ensuring local certificate exists: %w", err)
	}

	if localCertGenerated {
		certGenerated = true
	}

	// Extract all domains from the domain mappings
	var allDomains []string
	for _, mapping := range domainMappings {
		allDomains = append(allDomains, mapping.Domain)
	}

	// Generate domain-specific certificates
	for _, domain := range allDomains {
		domainCertGenerated, err := certManager.EnsureDomainCertificate(domain)
		if err != nil {
			return false, false, fmt.Errorf("error ensuring certificate for %s: %w", domain, err)
		}

		if domainCertGenerated {
			certGenerated = true
		}
	}

	// Generate provisioning profile for all domains
	if certGenerated || !profileManager.ProfileExists() {
		if err := profileManager.GenerateProfile(certManager.Paths.RootCAPath, mdnsHostnames[0], allDomains); err != nil {
			return certGenerated, false, fmt.Errorf("error generating provisioning profile: %w", err)
		}
		profileGenerated = !profileManager.ProfileExists()
	}

	// Get relative path for local TLS certificate and key
	localTLSCertPath, err := filepath.Rel(cwd, certManager.Paths.LocalCertPath)
	if err != nil {
		return certGenerated, profileGenerated, fmt.Errorf("error getting relative path for local certificate: %w", err)
	}

	localTLSKeyPath, err := filepath.Rel(cwd, certManager.Paths.LocalKeyPath)
	if err != nil {
		return certGenerated, profileGenerated, fmt.Errorf("error getting relative path for local key: %w", err)
	}

	// Create domain configurations for the template
	var domainConfigs []CaddyDomainConfig
	for _, domainMapping := range domainMappings {
		certPath, keyPath := certManager.GetDomainCertPaths(domainMapping.Domain)

		// Convert to relative paths
		relCertPath, err := filepath.Rel(cwd, certPath)
		if err != nil {
			return certGenerated, profileGenerated, fmt.Errorf("error getting relative path for domain certificate: %w", err)
		}

		relKeyPath, err := filepath.Rel(cwd, keyPath)
		if err != nil {
			return certGenerated, profileGenerated, fmt.Errorf("error getting relative path for domain key: %w", err)
		}

		domainConfigs = append(domainConfigs, CaddyDomainConfig{
			Domain:       domainMapping.Domain,
			CertPath:     relCertPath,
			KeyPath:      relKeyPath,
			PortMappings: domainMapping.PortMappings,
		})
	}

	const caddyTemplate = `# This Caddyfile was automatically generated by mdns-caddy
# To regenerate: run the mdns-caddy application
{
	admin off
	# Disable automatic HTTPS on port 443
	auto_https disable_redirects
}

# mDNS hostnames (serve HTTP, DNS over HTTPS, and profile download)
{{ range .MDNSHostnames }}
{{ . }} {
	tls {{ $.LocalTLSCertPath }} {{ $.LocalTLSKeyPath }}

	# Handle DNS-over-HTTPS requests
	handle /dns-query {
		reverse_proxy localhost:{{ $.ServerPort }}
	}

	# Handle all other paths
	handle {
		reverse_proxy localhost:{{ $.ServerPort }}
	}
}
{{ end }}

# Target domains with their port mappings
{{ range .DomainConfigs }}
{{ $domain := .Domain }}
{{ $certPath := .CertPath }}
{{ $keyPath := .KeyPath }}

# Setup server blocks for each port mapping for this domain
{{ range .PortMappings }}
{{ $domain }}:{{ .ExternalPort }} {
	tls {{ $certPath }} {{ $keyPath }}

	# Forward all traffic to the internal port
	reverse_proxy http://localhost:{{ .InternalPort }}
}
{{ end }}
{{ end }}
`
	tmpl, err := template.New("caddy").Parse(caddyTemplate)
	if err != nil {
		return certGenerated, profileGenerated, fmt.Errorf("error parsing Caddy template: %w", err)
	}

	dir := filepath.Dir(outputPath)
	if err := os.MkdirAll(dir, 0755); err != nil {
		return certGenerated, profileGenerated, fmt.Errorf("error creating directory %s: %w", dir, err)
	}

	file, err := os.Create(outputPath)
	if err != nil {
		return certGenerated, profileGenerated, fmt.Errorf("error creating Caddy config file: %w", err)
	}
	defer file.Close()

	config := Config{
		MDNSHostnames:    mdnsHostnames,
		ServerPort:       serverPort,
		LocalTLSCertPath: localTLSCertPath,
		LocalTLSKeyPath:  localTLSKeyPath,
		DomainConfigs:    domainConfigs,
	}
	if err := tmpl.Execute(file, config); err != nil {
		return certGenerated, profileGenerated, fmt.Errorf("error executing Caddy template: %w", err)
	}

	return certGenerated, profileGenerated, nil
}
