package caddy

import (
	"fmt"
	"os"
	"path/filepath"
	"text/template"
	
	"github.com/aran/mdns-caddy/internal/cert"
	"github.com/aran/mdns-caddy/internal/profile"
)

type Config struct {
	Hostnames   []string
	Port        int
	TLSCertPath string
	TLSKeyPath  string
}

const DefaultConfigPath = "Caddyfile"

func GenerateConfig(hostnames []string, port int, outputPath string) (bool, bool, error) {
	if len(hostnames) == 0 {
		return false, false, fmt.Errorf("no hostnames provided for Caddy configuration")
	}

	cwd, err := os.Getwd()
	if err != nil {
		return false, false, fmt.Errorf("error getting current directory: %w", err)
	}

	certManager := cert.NewManager(cwd)
	profileManager := profile.NewProfileManager(cwd)
	
	certGenerated := false
	profileGenerated := false

	_, err = os.Stat(certManager.Paths.RootCAPath)
	if err != nil {
		certGenerated = true
	}

	if err := certManager.EnsureCA(); err != nil {
		return false, false, fmt.Errorf("error ensuring CA exists: %w", err)
	}

	_, err = os.Stat(certManager.Paths.LeafCertPath)
	if err != nil {
		certGenerated = true
	}

	if err := certManager.EnsureCertificate(hostnames); err != nil {
		return false, false, fmt.Errorf("error ensuring certificate exists: %w", err)
	}

	if certGenerated || !profileManager.ProfileExists() {
		if err := profileManager.GenerateProfile(certManager.Paths.RootCAPath); err != nil {
			return certGenerated, false, fmt.Errorf("error generating provisioning profile: %w", err)
		}
		profileGenerated = !profileManager.ProfileExists()
	}

	tlsCertPath, err := filepath.Rel(cwd, certManager.Paths.LeafCertPath)
	if err != nil {
		return certGenerated, profileGenerated, fmt.Errorf("error getting relative path for leaf certificate: %w", err)
	}
	
	tlsKeyPath, err := filepath.Rel(cwd, certManager.Paths.LeafKeyPath)
	if err != nil {
		return certGenerated, profileGenerated, fmt.Errorf("error getting relative path for leaf key: %w", err)
	}

	const caddyTemplate = `# This Caddyfile was automatically generated by mdns-caddy
# To regenerate: run the mdns-caddy application
{
	admin off
}


{{ range .Hostnames }}
# Serve hostname over HTTPS with self-signed certificate
{{ . }} {
	tls {{ $.TLSCertPath }} {{ $.TLSKeyPath }}
	reverse_proxy localhost:{{ $.Port }}
}


{{ end }}
`
	tmpl, err := template.New("caddy").Parse(caddyTemplate)
	if err != nil {
		return certGenerated, profileGenerated, fmt.Errorf("error parsing Caddy template: %w", err)
	}

	dir := filepath.Dir(outputPath)
	if err := os.MkdirAll(dir, 0755); err != nil {
		return certGenerated, profileGenerated, fmt.Errorf("error creating directory %s: %w", dir, err)
	}

	file, err := os.Create(outputPath)
	if err != nil {
		return certGenerated, profileGenerated, fmt.Errorf("error creating Caddy config file: %w", err)
	}
	defer file.Close()

	config := Config{
		Hostnames:   hostnames,
		Port:        port,
		TLSCertPath: tlsCertPath,
		TLSKeyPath:  tlsKeyPath,
	}
	if err := tmpl.Execute(file, config); err != nil {
		return certGenerated, profileGenerated, fmt.Errorf("error executing Caddy template: %w", err)
	}

	return certGenerated, profileGenerated, nil
}